### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by maunakai** [mmaumio/exclusive-addons-for-elementor#27]
Hello, problem with last update from Elementor 3.16.4 (please note I do not use Elementor pro).
See file in attach.
Regards
![2023-09-25_094500](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/37689935/7ff0fa16-977d-401f-aadf-0966d3541d12)

**Comment by devjennz** [comment]
This issue belongs to **Exclusive Addons Elementor Pro**. Please download version v1.5.6 which includes the fix.
