### ISSUE TITLE
cross site copy paste not working

### ISSUE THREAD

**Issue by pramodrimal** [mmaumio/exclusive-addons-for-elementor#28]
Hello Cross Site copy paste function not working on the pro version. On older website still working but for the fresh download it is not working. donot get option for exclusive copy or paste option.

**Comment by devjennz** [comment]
Hello @pramodrimal , the issue is fixed. Cross Site Copy Paste extension now support Elementor containers. Please download Exclusive Addons Elementor Pro v1.5.7
