### ISSUE TITLE
SLIDER- Odd Arrows Symbol in Firefox

### ISSUE THREAD

**Issue by BlinkMore** [mmaumio/exclusive-addons-for-elementor#29]
I've noticed in Firefox, the arrow symbol on the slider is displaying a symbol that is not an arrow. I've attached an image of it. Navigation is set to arrows only. However, this may occur when any option of arrows is selected. Firefox version: 124.0 (64-bit). 
![Screenshot 2024-03-20 at 9 52 40 AM](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/116369814/a06aa391-0e62-4efb-9614-1cb324685e3c)

**Comment by devjennz** [comment]
Hello @BlinkMore 

The arrow symbol on the slider in Exclusive Addons Elementor Pro depends of Elementor Icons. If they are not available, it shows another symbol.

Now Exclusive Addons Elementor Pro got improved and has a fallback fix for it. 

Please download the latest release version 1.5.9

Thank you for reporting!
