### ISSUE TITLE
Countdown and other widgets not publishing like the preview/builder

### ISSUE THREAD

**Issue by LachlanPG** [mmaumio/exclusive-addons-for-elementor#30]
When I add the widget it looks good but then I preview or publish and it is entirely wrong!

![preview](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/109642803/1aa39f53-1af3-4692-a387-028d4143314a)
![Added](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/109642803/161ba701-77f6-4dd4-8150-36459e5113c4)

**Comment by devjennz** [comment]
Hi @LachlanPG !

I wasn't able to reproduce your issue. I recommend the following solutions:
– [Clear Elementor Cache]( https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor/) ( https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor )
– Clear Browser cache

Please let me know if you still see the issue.
