### ISSUE TITLE
the sections that uses "link anything" feature for redirection on click doesn't work anymore after the latest update

### ISSUE THREAD

**Issue by muneerWebDev** [mmaumio/exclusive-addons-for-elementor#31]
![image](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/40076031/6fb97d36-12b5-4ffd-babf-c12b800f1d4f)

**Comment by devjennz** [comment]
hello @muneerWebDev !

The issue is fixed.

Please download the latest release version 2.6.9.4

Thank you for reporting!

**Comment by muneerWebDev** [comment]
hey  @devjennz ! i updated plugin "Exclusive Addons Elementor" to 2.6.9.4 from 2.6.9, and it still gives me error

**Comment by muneerWebDev** [comment]
FYI - i also tried clearing Elementor and other caches

**Comment by devjennz** [comment]
Hi @muneerWebDev !

Yes I'm sorry the main minified front-end script file wasn't updated.

Until version 2.6.9.5 is live, please download the following plugin file which is v2.6.9.4 including front-end script updated.
[deleted]

**Comment by muneerWebDev** [comment]
thanks @devjennz !

**Comment by muneerWebDev** [comment]
i am using "Exclusive Addons Elementor **Pro**". is that why its still not working for me?

**Comment by devjennz** [comment]
Hi @muneerWebDev !

I see it working only when I do mouse over "Industries" and then click the options links. Clicking on "Industries" and then any of the links won't work.

The following link includes the fix for this issue:
[exclusive-addons-for-elementor-2.6.9.4.zip](https://github.com/timstrifler/exclusive-addons-for-elementor/files/15038557/exclusive-addons-for-elementor-2.6.9.4.zip)

**Comment by muneerWebDev** [comment]
hey @devjennz ! thanks for ur prompt response! Unfortunately, the link doesn't work regardless of click or hover. and i tried the latest files u provided as well, no change

**Comment by devjennz** [comment]
Hi @muneerWebDev ! 

I don't see the following file updated:
https://findyouraudience.online/wp-content/plugins/exclusive-addons-for-elementor/assets/js/exad-scripts.min.js?ver=2.6.9.4

Probably Elementor or Server cache. 
For elementor I recommend the following solutions:
– [Clear Elementor Cache](https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor/) ( https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor )

Then please proceed to clear Browser cache.

Please let me know how it goes.

**Comment by muneerWebDev** [comment]
Hi @devjennz ! I downgraded the plugin because it's live site and the plugin is causing broken links. I can dm u the staging site url or should I just send it here

**Comment by muneerWebDev** [comment]
@devjennz ?

**Comment by devjennz** [comment]
hi @muneerWebDev 

Your issue has been identified and it will be fixed on the following release 2.6.9.6.

Meanwhile you can use the following release:
[exclusive-addons-for-elementor.2.6.9.5.zip](https://github.com/timstrifler/exclusive-addons-for-elementor/files/15070116/exclusive-addons-for-elementor.2.6.9.5.zip)

**Comment by muneerWebDev** [comment]
this is working. thanks @devjennz !
