### ISSUE TITLE
Wrong dynamic URLs with "link anything" feature

### ISSUE THREAD

**Issue by muneerWebDev** [mmaumio/exclusive-addons-for-elementor#32]
clicking on the elements using dynamic url with "link aything" feature is  redirecting to the wrong url .

eg: 
giving wrong url - https://domainname.com/https%3A/domainname.com/products/smart-factory-suite/
where as actual url is - http://domainname.com/products/smart-factory-suite

**Comment by muneerWebDev** [comment]
![Screenshot 2024-04-25 211028](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/40076031/59f64a4c-e55c-4683-9772-ced8e33e75e2)

**Comment by devjennz** [comment]
Hello @muneerWebDev , the issue is fixed. 
Please update to the latest release v2.6.9.6
