### ISSUE TITLE
The Accordion Title Icon dosen't show ANYMORE !!

### ISSUE THREAD

**Issue by skarafahmed** [mmaumio/exclusive-addons-for-elementor#33]
Hey @devjennz 

The Accordion Title Icon doesn't show anymore on the latest update - 2.6.9.6 !!
I had to downgrade it to (2.6.9.2)
![SCR-20240507-plza](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/101312857/5e763761-c442-4529-9688-bfa73ce82432)

**Comment by devjennz** [comment]
Hi @skarafahmed ,

I wasn't able to reproduce your issue on my end. I would like to know if you can try the following:

– [Clear Elementor Cache](https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor/) ( https://elementor.com/help/caching-prevents-live-site-from-showing-changes-in-editor )

Then proceed to clear Browser cache.

Please let me know if the issue continue and I'll review it again.

**Comment by devjennz** [comment]
Please update to the latest release v2.6.9.7
