### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by 3xploiton3** [mmaumio/exclusive-addons-for-elementor#34]
Creation of dynamic property ExclusiveAddons\Pro\Elementor\Plugin_Updater::$beta is deprecated

![image](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/19517680/d7c42075-3aa0-4a73-b0b0-6a2d7b12b2af)

**Comment by devjennz** [comment]
Hi @3xploiton3 ,

Thank you for reporting. The issue has been identified in **Exclusive Addons Elementor Pro** and it will be fixed on the next version.

Closing this because the issue is specific on Pro version.
