### ISSUE TITLE
Post Duplicator saves post_meta as array instead of string

### ISSUE THREAD

**Issue by pdesaulniers-vertisoft** [mmaumio/exclusive-addons-for-elementor#35]
**Exclusive Addons Elementor 2.6.9.7**

It seems like `Post Duplicator` does not copy post_meta correctly. This can lead to issues such as: https://github.com/woocommerce/woocommerce/issues/47974

To reproduce the issue:

- Create a post with some metadata (for instance: `meta_key` = `hello` and `meta_value` = `world`)
- Duplicate the post by clicking on Ex Duplicator
- The meta value will be equal to `a:1:{i:0;s:5:"world";}` instead of `world` in the duplicate post

We think the problem is caused by this code in `Post Duplicator`: https://github.com/timstrifler/exclusive-addons-for-elementor/blob/e8986376e46780a5d4cbd4d4094da2030b1f2213/extensions/post-duplicator.php#L110-L118

`get_post_meta` is called without specifiying `$key` and `$single`. In that case, it returns post metas as arrays, rather than strings, since one meta_key can appear multiple times in the database for a single post.

So, when `update_post_meta` is called, `$meta_value` is of type 'array', rather than 'string'.

Thus, `_manage_stock => yes` in the original post, is stored as `_manage_stock => a:1:{i:0;s:3:"yes";}` in the duplicated post.

**Comment by devjennz** [comment]
Hi @pdesaulniers-vertisoft

Your issue has been identified and it's fixed on version 2.6.9.8

Thank you for reporting.
