### ISSUE TITLE
Cannot activate the plugin and WebGL

### ISSUE THREAD

**Issue by worpdresshero** [mmaumio/exclusive-addons-for-elementor#36]
I activated the exclusive add-on and web gl with key codes before wiping the website. It is giving me issues with activating the plugins again after I reinstalled WordPress

![Issue](https://github.com/timstrifler/exclusive-addons-for-elementor/assets/172723803/ad4d7333-18b9-4cef-82ca-86339aecaaa9)

**Comment by devjennz** [comment]
hi @worpdresshero 

Please reach us on our Official Support System:
https://exclusiveaddons.com/support/
