### ISSUE TITLE
Disables Elementor Sidebar

### ISSUE THREAD

**Issue by iamdcast** [mmaumio/exclusive-addons-for-elementor#37]
![3fd67275-6b08-4295-9579-a5d3ee2b778d](https://github.com/user-attachments/assets/de67ce24-dc99-4058-b808-2d1348ed0194)

We recently purchased this but as soon as we installed we realized it disabled our elementor sidebar. Any recommended fix for this?

Thank you,

**Comment by devjennz** [comment]
hi @iamdcast , 

I would like to replicate your issue and I need to know the following:

- Wordpress version
- Plugins installed (including version of each one)

If you have a Staging or Development site where you were able to replicate the issue, then you can reach us on our Official Support channels and send a temporal admin access.

**Comment by devjennz** [comment]
Let us know if you need anything else.

I’m going to close this thread on here.
