### ISSUE TITLE
CSS code that adds an icon to the Icon Box with the selector .icon-box

### ISSUE THREAD

**Issue by StealUrKill** [mmaumio/exclusive-addons-for-elementor#38]
Using the Plugin with the JKit plugin and using JKits Icon Box, exclusive addons adds an icon to the JKit Icon box. Please see attached link from JKit devoloper. I hope what ever he explained is correct. His css code fixed the issue.

https://wordpress.org/support/topic/jkit-icon-box-artifaces/#post-17976045

Thank you for providing us with your website URL and the plugins you use. After investigating, we found that the issue is caused by a conflict with the Exclusive Addons for Elementor plugin. This plugin includes CSS code that adds an icon to the Icon Box with the selector .icon-box, which coincidentally is the same selector used by the JKit - Icon Box widget, resulting in this issue.

`/** JKit || Fix Icon Box Conflict with Exclusive Addons Elementor plugin */
.jeg-elementor-kit.jkit-icon-box .icon-box:before {
    content: '';
}`

![image](https://github.com/user-attachments/assets/a57d9e6a-5ada-4d87-9b0d-2a8b662b04c6)

**Comment by devjennz** [comment]
Hi @StealUrKill ,

Thank you for reporting. Since this issue is related to **JKit plugin** and changing the name of the selector .icon-box will affect all our user installations, it won't be fixed for now.
